# fly.toml app configuration file generated for taia-cms-summer-forest-4269 on 2025-02-01T14:39:59+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'taia-cms-summer-forest-4269'
primary_region = 'gru'
kill_timeout = '5m0s'

[build]

[[mounts]]
  source = 'media'
  destination = '/opt/app/media'
  initial_size = '1gb'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 1337
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
